### PR TITLE
fix: create dir bug

### PR DESCRIPTION
**Pull request by shynome**

### CODE REVIEW

**Comment by firmanmm** [comment]
Hi, could you provide some description on what problems it trying to fix and why did you propose this solution? Thank you!

**Comment by shynome** [comment]
`os.Link` will failed in this created directory on linux

**Comment by firmanmm** [comment]
I see, I'm a bit concerned with the permission especially with `0777`. Currently, I didn't get any error with current permission (`0666`) in `Ubuntu 20.04.2 LTS`. Can we just use `0766`?

**Comment by shynome** [comment]
you are right, but I don't know about file mode, I'm just a go curd developer

**Pull request closed without merging**
